<?php
//  man page data — included by the 'man' case in shell.php
//  Returns: $pages array keyed by command name

$pages = [
    'cp'      => "CP(1)                     User Commands                    CP(1)\n\nNAME\n       cp - copy files and directories\n\nSYNOPSIS\n       cp [OPTION]... SOURCE DEST\n       cp [OPTION]... SOURCE... DIRECTORY\n\nDESCRIPTION\n       Copy SOURCE to DEST, or multiple SOURCE(s) to DIRECTORY.\n\n       -r, -R, --recursive\n              copy directories recursively\n\n       -f, --force\n              if an existing destination file cannot be opened, remove it\n              and try again\n\n       -v, --verbose\n              explain what is being done\n\n       -p, --preserve\n              preserve the specified attributes (default: mode, ownership,\n              timestamps)\n\n       -u, --update\n              copy only when the SOURCE file is newer than the destination\n              file or when the destination file is missing\n\nAUTHOR\n       Written by Torbjorn Granlund, David MacKenzie, and Jim Meyering.\n\nGNU coreutils                    March 2026                          CP(1)",

    'mv'      => "MV(1)                     User Commands                    MV(1)\n\nNAME\n       mv - move (rename) files\n\nSYNOPSIS\n       mv [OPTION]... SOURCE DEST\n       mv [OPTION]... SOURCE... DIRECTORY\n\nDESCRIPTION\n       Rename SOURCE to DEST, or move SOURCE(s) to DIRECTORY.\n\n       -f, --force\n              do not prompt before overwriting\n\n       -i, --interactive\n              prompt before overwrite\n\n       -n, --no-clobber\n              do not overwrite an existing file\n\n       -v, --verbose\n              explain what is being done\n\n       -u, --update\n              move only when the SOURCE file is newer than the destination\n              file or when the destination file is missing\n\nAUTHOR\n       Written by Mike Parker, David MacKenzie, and Jim Meyering.\n\nGNU coreutils                    March 2026                          MV(1)",

    'ls'      => "LS(1)                     User Commands                    LS(1)\n\nNAME\n       ls - list directory contents\n\nSYNOPSIS\n       ls [OPTION]... [FILE]...\n\nDESCRIPTION\n       List  information  about  the FILEs (the current directory by default).\n       Sort entries alphabetically if none of -cftuvSUX nor --sort  is  speci-\n       fied.\n\n       -a, --all\n              do not ignore entries starting with .\n\n       -l     use a long listing format\n\n       -h, --human-readable\n              with -l and -s, print sizes like 1K 234M 2G etc.\n\n       -r, --reverse\n              reverse order while sorting\n\n       -t     sort by time, newest first\n\nAUTHOR\n       Written by Richard M. Stallman and David MacKenzie.\n\nGNU coreutils                    March 2026                          LS(1)",

    'cat'     => "CAT(1)                    User Commands                   CAT(1)\n\nNAME\n       cat - concatenate files and print on the standard output\n\nSYNOPSIS\n       cat [OPTION]... [FILE]...\n\nDESCRIPTION\n       Concatenate FILE(s) to standard output.\n\n       -n, --number\n              number all output lines\n\n       -v, --show-nonprinting\n              use ^ and M- notation, except for LFD and TAB\n\nAUTHOR\n       Written by Torbjorn Granlund and Richard M. Stallman.\n\nGNU coreutils                    March 2026                         CAT(1)",

    'cd'      => "CD(1)                     bash built-in                    CD(1)\n\nNAME\n       cd - change the shell working directory\n\nSYNOPSIS\n       cd [-L|[-P [-e]] [-@]] [dir]\n\nDESCRIPTION\n       Change  the  current  directory  to dir.  The default DIR is the value\n       of the HOME shell variable.\n\n       -L     force symbolic links to be followed\n       -P     use the physical directory structure\n\nGNU bash                         March 2026                          CD(1)",

    'pwd'     => "PWD(1)                    User Commands                   PWD(1)\n\nNAME\n       pwd - print name of current/working directory\n\nSYNOPSIS\n       pwd [OPTION]...\n\nDESCRIPTION\n       Print the full filename of the current working directory.\n\n       -L, --logical\n              use PWD from environment, even if it contains symlinks\n\n       -P, --physical\n              avoid all symlinks\n\nAUTHOR\n       Written by Jim Meyering.\n\nGNU coreutils                    March 2026                         PWD(1)",

    'mkdir'   => "MKDIR(1)                  User Commands                 MKDIR(1)\n\nNAME\n       mkdir - make directories\n\nSYNOPSIS\n       mkdir [OPTION]... DIRECTORY...\n\nDESCRIPTION\n       Create the DIRECTORY(ies), if they do not already exist.\n\n       -m, --mode=MODE\n              set file mode (as in chmod), not a=rwx - umask\n\n       -p, --parents\n              no error if existing, make parent directories as needed\n\n       -v, --verbose\n              print a message for each created directory\n\nAUTHOR\n       Written by David MacKenzie.\n\nGNU coreutils                    March 2026                       MKDIR(1)",

    'rm'      => "RM(1)                     User Commands                    RM(1)\n\nNAME\n       rm - remove files or directories\n\nSYNOPSIS\n       rm [OPTION]... [FILE]...\n\nDESCRIPTION\n       This manual page documents the GNU version of rm.  rm removes each\n       specified file.  By default, it does not remove directories.\n\n       -f, --force\n              ignore nonexistent files and arguments, never prompt\n\n       -r, -R, --recursive\n              remove directories and their contents recursively\n\n       -v, --verbose\n              explain what is being done\n\nWARNING\n       If you use rm to remove a file, it might be possible to  recover  some\n       of its contents.\n\nAUTHOR\n       Written by Paul Rubin, David MacKenzie, Richard Stallman, Jim Meyering.\n\nGNU coreutils                    March 2026                          RM(1)",

    'touch'   => "TOUCH(1)                  User Commands                 TOUCH(1)\n\nNAME\n       touch - change file timestamps\n\nSYNOPSIS\n       touch [OPTION]... FILE...\n\nDESCRIPTION\n       Update the access and modification times of each FILE to the current\n       time.  A FILE argument that does not exist is created empty.\n\n       -a     change only the access time\n\n       -m     change only the modification time\n\n       -t STAMP\n              use [[CC]YY]MMDDhhmm[.ss] instead of current time\n\nAUTHOR\n       Written by Paul Rubin, Arnold Robbins, Jim Kingdon, David MacKenzie,\n       and Randy Smith.\n\nGNU coreutils                    March 2026                       TOUCH(1)",

    'grep'    => "GREP(1)                   User Commands                  GREP(1)\n\nNAME\n       grep, egrep, fgrep - print lines that match patterns\n\nSYNOPSIS\n       grep [OPTION...] PATTERNS [FILE...]\n\nDESCRIPTION\n       grep  searches  for  PATTERNS  in  each FILE.\n\n       -i, --ignore-case\n              ignore case distinctions in patterns and data\n\n       -r, --recursive\n              read all files under each directory, recursively\n\n       -n, --line-number\n              print line number with output lines\n\n       -v, --invert-match\n              select non-matching lines\n\n       -c, --count\n              print only a count of selected lines per FILE\n\nAUTHOR\n       Written by Mike Haertel and others.\n\nGNU grep                         March 2026                        GREP(1)",

    'ssh'     => "SSH(1)                    User Commands                   SSH(1)\n\nNAME\n       ssh - OpenSSH remote login client\n\nSYNOPSIS\n       ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-p port] [-i identity_file]\n           [-l login_name] destination [command]\n\nDESCRIPTION\n       ssh  (SSH client) is a program for logging into a remote machine and\n       for executing commands on a remote machine.\n\n       -p port\n              Port to connect to on the remote host.\n\n       -i identity_file\n              Selects a file from which the identity (private key) for\n              public key authentication is read.\n\n       -v     Verbose mode.\n\nOpenSSH                          March 2026                         SSH(1)",

    'ping'    => "PING(8)               System Manager's Manual              PING(8)\n\nNAME\n       ping - send ICMP ECHO_REQUEST to network hosts\n\nSYNOPSIS\n       ping [-c count] [-i interval] [-t ttl] {destination}\n\nDESCRIPTION\n       ping uses the ICMP protocol's mandatory ECHO_REQUEST datagram\n       to elicit an ICMP ECHO_RESPONSE from a host or gateway.\n\n       -c count\n              Stop after sending count ECHO_REQUEST packets.\n\n       -i interval\n              Wait interval seconds between sending each packet.\n\n       -t ttl\n              Set the IP Time to Live.\n\nIPutils                          March 2026                        PING(8)",

    'df'      => "DF(1)                     User Commands                    DF(1)\n\nNAME\n       df - report file system space usage\n\nSYNOPSIS\n       df [OPTION]... [FILE]...\n\nDESCRIPTION\n       df displays the amount of space available on the file system.\n\n       -h, --human-readable\n              print sizes in powers of 1024 (e.g., 1023M)\n\n       -T, --print-type\n              print file system type\n\n       -i, --inodes\n              list inode information instead of block usage\n\nAUTHOR\n       Written by Torbjorn Granlund, David MacKenzie, and Paul Eggert.\n\nGNU coreutils                    March 2026                          DF(1)",

    'free'    => "FREE(1)                   User Commands                  FREE(1)\n\nNAME\n       free - Display amount of free and used memory in the system\n\nSYNOPSIS\n       free [options]\n\nDESCRIPTION\n       free displays the total amount of free and used physical and swap\n       memory in the system.\n\n       -b, --bytes\n              Display the amount of memory in bytes.\n\n       -h, --human\n              Show all output fields automatically scaled to shortest\n              three digit unit.\n\nAUTHOR\n       Written by Brian Edmonds.\n\nprocps-ng                        March 2026                        FREE(1)",

    'ps'      => "PS(1)                     User Commands                    PS(1)\n\nNAME\n       ps - report a snapshot of the current processes\n\nSYNOPSIS\n       ps [options]\n\nDESCRIPTION\n       ps displays information about a selection of the active processes.\n\n       a      Lift the BSD-style \"only yourself\" restriction.\n       u      Display user-oriented format.\n       x      Lift the BSD-style \"must have a tty\" restriction.\n\n       -e     Select all processes.\n       -f     Full-format listing.\n\nAUTHOR\n       ps was originally written by Branko Lankester.\n\nprocps-ng                        March 2026                          PS(1)",

    'top'     => "TOP(1)                    User Commands                   TOP(1)\n\nNAME\n       top - display Linux processes\n\nSYNOPSIS\n       top -hv|-bcEeHiOSs1 -d secs -n max -u|U user -p pids -o field\n\nDESCRIPTION\n       The top program provides a dynamic real-time view of a running system.\n\nINTERACTIVE COMMANDS\n       q      Quit\n       k      Kill a task\n       r      Renice a task\n       SPACE  Refresh display\n\nAUTHOR\n       Written by Roger Binns.\n\nprocps-ng                        March 2026                         TOP(1)",

    'uname'   => "UNAME(1)                  User Commands                 UNAME(1)\n\nNAME\n       uname - print system information\n\nSYNOPSIS\n       uname [OPTION]...\n\nDESCRIPTION\n       Print certain system information.\n\n       -a, --all\n              print all information\n\n       -s, --kernel-name\n              print the kernel name\n\n       -n, --nodename\n              print the network node hostname\n\n       -r, --kernel-release\n              print the kernel release\n\n       -m, --machine\n              print the machine hardware name\n\nAUTHOR\n       Written by David MacKenzie.\n\nGNU coreutils                    March 2026                       UNAME(1)",

    'chmod'   => "CHMOD(1)                  User Commands                 CHMOD(1)\n\nNAME\n       chmod - change file mode bits\n\nSYNOPSIS\n       chmod [OPTION]... MODE[,MODE]... FILE...\n\nDESCRIPTION\n       chmod changes the file mode bits of each given file according to mode.\n\n       -R, --recursive\n              change files and directories recursively\n\n       -v, --verbose\n              output a diagnostic for every file processed\n\nAUTHOR\n       Written by David MacKenzie and Jim Meyering.\n\nGNU coreutils                    March 2026                       CHMOD(1)",

    'curl'    => "CURL(1)                   User Commands                  CURL(1)\n\nNAME\n       curl - transfer a URL\n\nSYNOPSIS\n       curl [options / URLs]\n\nDESCRIPTION\n       curl  is  a tool for transferring data from or to a server using URLs.\n\n       -o, --output <file>\n              Write output to <file> instead of stdout.\n\n       -O, --remote-name\n              Write output to a local file named like the remote file.\n\n       -s, --silent\n              Silent mode.\n\n       -L, --location\n              Follow redirects.\n\n       -v, --verbose\n              Makes curl verbose during the operation.\n\nAUTHOR\n       Written by Daniel Stenberg.\n\ncurl                             March 2026                        CURL(1)",

    'wget'    => "WGET(1)                   User Commands                  WGET(1)\n\nNAME\n       wget - The non-interactive network downloader.\n\nSYNOPSIS\n       wget [option]... [URL]...\n\nDESCRIPTION\n       GNU  Wget  is  a  free  utility  for  non-interactive download of\n       files from the Web.\n\n       -q, --quiet\n              Turn off Wget's output.\n\n       -O file, --output-document=file\n              Write documents to file.\n\n       -r, --recursive\n              Turn on recursive retrieving.\n\n       -c, --continue\n              Continue getting a partially-downloaded file.\n\nAUTHOR\n       Written by Hrvoje Niksic.\n\nGNU Wget                         March 2026                        WGET(1)",

    'sudo'    => "SUDO(8)               System Manager's Manual              SUDO(8)\n\nNAME\n       sudo, sudoedit - execute a command as another user\n\nSYNOPSIS\n       sudo [-u user] command [argument ...]\n\nDESCRIPTION\n       sudo allows a permitted user to execute a command as the superuser\n       or another user.\n\n       -u user, --user=user\n              Run the command as a user other than the default target\n              user (usually root).\n\n       -l, --list\n              List the allowed (and forbidden) commands for the invoking user.\n\nTODD C. MILLER                   March 2026                        SUDO(8)",

    'history' => "HISTORY(3)             bash built-in                 HISTORY(3)\n\nNAME\n       history - GNU History Library\n\nSYNOPSIS\n       history [-c] [-d offset] [n]\n       history -anrw [filename]\n\nDESCRIPTION\n       Without options, display the command history list with line numbers.\n\n       -c     Clear the history list by deleting all the entries.\n\n       -d offset\n              Delete the history entry at position offset.\n\n       -a     Append the 'new' history lines to the history file.\n\nGNU bash                         March 2026                     HISTORY(3)",

    'echo'    => "ECHO(1)                   User Commands                  ECHO(1)\n\nNAME\n       echo - display a line of text\n\nSYNOPSIS\n       echo [SHORT-OPTION]... [STRING]...\n\nDESCRIPTION\n       Echo the STRING(s) to standard output.\n\n       -n     do not output the trailing newline\n\n       -e     enable interpretation of backslash escapes\n\n       -E     disable interpretation of backslash escapes (default)\n\nAUTHOR\n       Written by Brian Fox and Chet Ramey.\n\nGNU coreutils                    March 2026                        ECHO(1)",

    'nano'    => "NANO(1)                   User Commands                  NANO(1)\n\nNAME\n       nano - Nano's ANOther editor, an enhanced free Pico clone\n\nSYNOPSIS\n       nano [OPTIONS] [[+LINE[,COL]] FILE]...\n\nDESCRIPTION\n       nano is a small and friendly editor. It copies the look and feel\n       of Pico, but is free software.\n\nKEYBINDINGS\n       ^G (F1)   Display this help text\n       ^X (F2)   Close the current file buffer / Exit from nano\n       ^O (F3)   Write the current file to disk\n       ^W (F6)   Search forward for a string\n       ^K (F9)   Cut the current line and store it in the cutbuffer\n       ^U (F10)  Paste the contents of the cutbuffer\n       ^C (F11)  Display the position of the cursor\n\n       Arrow keys move the cursor. Home/End go to start/end of line.\n       PageUp/PageDown scroll by one screenful.\n\nAUTHOR\n       Written by Chris Allegretta. Current maintainer: Benno Schulenberg.\n\nGNU nano                         March 2026                        NANO(1)",

    'wc'      => "WC(1)                     User Commands                    WC(1)\n\nNAME\n       wc - print newline, word, and byte counts for each file\n\nSYNOPSIS\n       wc [OPTION]... [FILE]...\n\nDESCRIPTION\n       Print newline, word, and byte counts for each FILE, and a total\n       line if more than one FILE is specified.  With no FILE, read\n       standard input.\n\n       -c, --bytes\n              print the byte counts\n\n       -m, --chars\n              print the character counts\n\n       -l, --lines\n              print the newline counts\n\n       -w, --words\n              print the word counts\n\n       -L, --max-line-length\n              print the maximum display width\n\nAUTHOR\n       Written by Paul Rubin and David MacKenzie.\n\nGNU coreutils                    March 2026                          WC(1)",

    'more'    => "MORE(1)                   User Commands                  MORE(1)\n\nNAME\n       more - file perusal filter for crt viewing\n\nSYNOPSIS\n       more [options] file...\n\nDESCRIPTION\n       more is a filter for paging through text one screenful at a time.\n\n       -d     Prompt with '[Press space to continue, q to quit.]'\n\n       -p     Do not scroll. Instead, clear the whole screen and then\n              display the text.\n\n       +num   Start at line number num.\n\nINTERACTIVE COMMANDS\n       SPACE        display next k lines of text (default current screen size)\n       ENTER        display next k lines of text (default 1)\n       q or Q       exit more\n       /pattern     search for pattern in remaining text\n       =            display current line number\n       h or ?       display this help text\n\nAUTHOR\n       Written by Eric Shienbrood, Geoff Peck, John Foderaro.\n\nutil-linux                       March 2026                        MORE(1)",

    'less'    => "LESS(1)                   User Commands                  LESS(1)\n\nNAME\n       less - opposite of more\n\nSYNOPSIS\n       less [-[+]aABcCdeEfFgGiIJKLmMnNqQrRsSuUVwWX~]\n            [-b space] [-h lines] [-j line] [-k keyfile]\n            [-o logfile] [-p pattern] [-P prompt] [-t tag]\n            [-T tagsfile] [-x tab,...] [-y lines] [-[z] lines]\n            [+[+]cmd] [--] [filename]...\n\nDESCRIPTION\n       less is a program similar to more, but which allows backward\n       movement in the file as well as forward movement.\n\nINTERACTIVE COMMANDS\n       SPACE or f    Scroll forward one window\n       b             Scroll backward one window\n       ENTER or e    Scroll forward one line\n       y             Scroll backward one line\n       g             Go to first line\n       G             Go to last line\n       /pattern      Search forward for pattern\n       ?pattern      Search backward for pattern\n       n             Repeat previous search\n       q or Q        Exit less\n       h             Display this help\n\n       less is more feature-rich than more: it supports both forward\n       and backward navigation, search highlighting, and does not need\n       to read the entire file before displaying.\n\nAUTHOR\n       Written by Mark Nudelman.\n\nless                             March 2026                        LESS(1)",

    'cron'    => "CRON(8)               System Manager's Manual              CRON(8)\n\nNAME\n       cron - daemon to execute scheduled commands\n\nSYNOPSIS\n       cron [-n] [-p] [-s] [-m <mailcommand>]\n\nDESCRIPTION\n       cron is started automatically from /etc/init.d on entering\n       multi-user runlevels.  It searches /var/spool/cron for crontab\n       files which are named after accounts in /etc/passwd; the found\n       crontabs are loaded into the memory.\n\n       cron also searches for /etc/anacrontab and any files in the\n       /etc/cron.d directory.  These differ from user crontabs in that\n       they contain a username field in the entry.\n\nCRONTAB FORMAT\n       A crontab entry has the form:\n\n       minute  hour  day  month  weekday  command\n\n       Ranges, lists, and steps are allowed:\n         */5 * * * *    every 5 minutes\n         0 2 * * *      daily at 02:00\n         0 9 * * 1      every Monday at 09:00\n\nFILES\n       /etc/crontab          system crontab\n       /etc/cron.d/          additional crontab fragments\n       /etc/cron.hourly/     scripts run every hour\n       /etc/cron.daily/      scripts run every day\n       /etc/cron.weekly/     scripts run every week\n       /etc/cron.monthly/    scripts run every month\n       /var/spool/cron/      per-user crontabs\n\nSEE ALSO\n       crontab(1), anacron(8)\n\nPaul Vixie                       March 2026                        CRON(8)",

    'crontab' => "CRONTAB(1)                User Commands               CRONTAB(1)\n\nNAME\n       crontab - maintain crontab files for individual users\n\nSYNOPSIS\n       crontab [-u user] file\n       crontab [-u user] [-l | -r | -e] [-i]\n\nDESCRIPTION\n       crontab is the program used to install, remove or list the tables\n       used to drive the cron daemon.\n\n       -l     List the current crontab.\n\n       -e     Edit the current crontab using the editor specified by the\n              VISUAL or EDITOR environment variable.\n\n       -r     Remove the current crontab.\n\n       -u user\n              Specify the name of the user whose crontab is to be\n              modified.  If this option is not given, it defaults to\n              the current user.\n\nFILES\n       /var/spool/cron/crontabs/    user crontab storage\n\nSEE ALSO\n       cron(8)\n\nPaul Vixie                       March 2026                     CRONTAB(1)",

    'httpd'   => "HTTPD(8)              System Manager's Manual             HTTPD(8)\n\nNAME\n       httpd - Apache Hypertext Transfer Protocol Server\n\nSYNOPSIS\n       httpd [-d serverroot] [-f config] [-C directive] [-c directive]\n             [-D parameter] [-e level] [-E file] [-k signal]\n             [-T] [-t] [-S] [-X] [-v] [-V] [-h] [-l] [-L] [-M] [-n name]\n\nDESCRIPTION\n       httpd is the Apache HyperText Transfer Protocol (HTTP) server\n       program.  It is designed to be run as a standalone daemon process.\n\n       -d serverroot\n              Set the initial value for the ServerRoot directive.\n\n       -f config\n              Use the directives in the file config on startup.\n              Default: /etc/httpd/conf/httpd.conf\n\n       -k signal\n              Send signal to the running httpd.  Signals: start, restart,\n              graceful, graceful-stop, stop.\n\n       -t     Run syntax tests for configuration files only.\n\n       -v     Print the version of httpd and exit.\n\n       -M     List all loaded modules and exit.\n\nFILES\n       /etc/httpd/conf/httpd.conf      main configuration file\n       /etc/httpd/conf.d/              additional configuration\n       /etc/httpd/conf.modules.d/      module load configuration\n       /var/log/httpd/                 log files\n       /var/www/html/                  default document root\n\nSEE ALSO\n       apachectl(8)\n\nApache HTTP Server               March 2026                       HTTPD(8)",

    'apachectl' => "APACHECTL(8)          System Manager's Manual          APACHECTL(8)\n\nNAME\n       apachectl - Apache HTTP Server Control Interface\n\nSYNOPSIS\n       apachectl command\n\nDESCRIPTION\n       apachectl is a front end to the Apache HyperText Transfer\n       Protocol (HTTP) server.  It is designed to help the administrator\n       control the functioning of the Apache httpd daemon.\n\nCOMMANDS\n       start       Start the Apache daemon.\n       stop        Stop the Apache daemon.\n       restart     Restart the Apache daemon gracefully (SIGHUP).\n       graceful    Graceful restart — open connections are not aborted.\n       fullstatus  Display a full status report from mod_status.\n       status      Display a brief status report.\n       configtest  Run a configuration file syntax test (equivalent to\n                   httpd -t).\n\nFILES\n       /etc/httpd/conf/httpd.conf\n\nSEE ALSO\n       httpd(8)\n\nApache HTTP Server               March 2026                   APACHECTL(8)",

    'fastfetch' => "FASTFETCH(1)              User Commands              FASTFETCH(1)\n\nNAME\n       fastfetch - a fast system information tool\n\nSYNOPSIS\n       fastfetch [OPTIONS]\n\nDESCRIPTION\n       fastfetch is a neofetch-like tool written in C for showing system\n       information and an ASCII distribution logo. It is significantly\n       faster than neofetch due to parallel data acquisition.\n\n       The displayed information includes:\n         OS, Host, Kernel, Uptime, Packages, Shell, Resolution,\n         CPU, Memory, Disk, Load average.\n\nOPTIONS\n       --help\n              Print help message.\n\n       --version\n              Print version.\n\n       --config <path>\n              Load configuration from <path>.\n\n       --logo <name>\n              Override the ASCII logo shown.\n\nFILES\n       ~/.config/fastfetch/config.jsonc\n              User configuration file.\n\nSEE ALSO\n       neofetch(1)\n\nfastfetch                        March 2026                   FASTFETCH(1)",

    'neofetch'  => "NEOFETCH(1)               User Commands               NEOFETCH(1)\n\nNAME\n       neofetch - A fast, highly customizable system info script\n\nSYNOPSIS\n       neofetch [OPTIONS]\n\nDESCRIPTION\n       Neofetch is a command-line system information tool written in bash.\n       Neofetch displays information about your operating system, software\n       and hardware in an aesthetic and visually pleasing way.\n\n       The information is displayed alongside an ASCII image, a distro\n       logo, or any image or video (with w3m or Kitty graphics protocol).\n\nOPTIONS\n       --help\n              Print this text and exit.\n\n       --version\n              Show neofetch version.\n\n       --config /path/to/config\n              Specify a path to a custom config file.\n\n       --off  Disable the ascii image.\n\n       --ascii_distro distro\n              Choose an ascii distro to display.\n\nFILES\n       ~/.config/neofetch/config.conf\n              User configuration file.\n\nSEE ALSO\n       fastfetch(1)\n\nneofetch                         March 2026                    NEOFETCH(1)",

    'head'      => "HEAD(1)                   User Commands                  HEAD(1)\n\nNAME\n       head - output the first part of files\n\nSYNOPSIS\n       head [OPTION]... [FILE]...\n\nDESCRIPTION\n       Print the first 10 lines of each FILE to standard output.\n       With more than one FILE, precede each with a header giving the\n       file name.\n\n       -n, --lines=[-]NUM\n              print the first NUM lines instead of the first 10;\n              with the leading '-', print all but the last NUM lines\n\n       -c, --bytes=[-]NUM\n              print the first NUM bytes of each file;\n              with the leading '-', print all but the last NUM bytes\n\n       -q, --quiet, --silent\n              never print headers giving file names\n\n       -v, --verbose\n              always print headers giving file names\n\nEXAMPLES\n       head file.txt\n              Print first 10 lines of file.txt.\n\n       head -n 20 file.txt\n              Print first 20 lines.\n\n       head -c 100 file.txt\n              Print first 100 bytes.\n\n       head -n5 file.txt\n              Shorthand for -n 5.\n\nAUTHOR\n       Written by David MacKenzie and Jim Meyering.\n\nGNU coreutils                    March 2026                        HEAD(1)",

    'tail'      => "TAIL(1)                   User Commands                  TAIL(1)\n\nNAME\n       tail - output the last part of files\n\nSYNOPSIS\n       tail [OPTION]... [FILE]...\n\nDESCRIPTION\n       Print the last 10 lines of each FILE to standard output.\n       With more than one FILE, precede each with a header giving\n       the file name.\n\n       -n, --lines=[+]NUM\n              output the last NUM lines, instead of the last 10;\n              or use -n +NUM to output starting with line NUM\n\n       -c, --bytes=[+]NUM\n              output the last NUM bytes; or use -c +NUM to output\n              starting with byte NUM\n\n       -f, --follow\n              output appended data as the file grows (simulated —\n              shows last NUM lines with a follow notice)\n\n       -q, --quiet, --silent\n              never output headers giving file names\n\n       -v, --verbose\n              always output headers giving file names\n\nEXAMPLES\n       tail file.txt\n              Print last 10 lines of file.txt.\n\n       tail -n 20 file.txt\n              Print last 20 lines.\n\n       tail -f file.txt\n              Follow file output (simulated).\n\n       tail -c 25 file.txt\n              Print last 25 bytes.\n\n       tail -n +5 file.txt\n              Print from line 5 onwards.\n\n       tail -n10 file.txt\n              Shorthand for -n 10.\n\nAUTHOR\n       Written by Paul Rubin and David MacKenzie.\n\nGNU coreutils                    March 2026                        TAIL(1)",

    'systemctl' => "SYSTEMCTL(1)           systemd                        SYSTEMCTL(1)\n\nNAME\n       systemctl - Control the systemd system and service manager\n\nSYNOPSIS\n       systemctl [OPTIONS...] COMMAND [UNIT...]\n\nDESCRIPTION\n       systemctl may be used to introspect and control the state of the\n       systemd system and service manager.\n\nUNIT COMMANDS\n       start NAME...\n              Start (activate) one or more units specified on the\n              command line.\n\n       stop NAME...\n              Stop (deactivate) one or more units.\n\n       restart NAME...\n              Stop and then start one or more units.\n\n       status [NAME...|PID...]\n              Show terse runtime status information about one or more\n              units, followed by most recent journal log data from the\n              unit.\n\n       enable NAME...\n              Enable one or more units to start at boot.\n\n       disable NAME...\n              Disable one or more units from starting at boot.\n\n       is-active PATTERN...\n              Check whether any of the specified units are active.\n              Returns exit code 0 if at least one is active.\n\n       list-units [PATTERN...]\n              List units that systemd currently has in memory.\n\nEXAMPLES\n       systemctl status httpd\n              Show status of the Apache HTTP server.\n\n       systemctl restart php-fpm\n              Restart the PHP-FPM process manager.\n\n       systemctl enable mariadb\n              Enable MariaDB to start at boot.\n\nFILES\n       /usr/lib/systemd/system/       unit files shipped with packages\n       /etc/systemd/system/           unit files for local configuration\n\nSEE ALSO\n       systemd(1), journalctl(1)\n\nsystemd                          March 2026                    SYSTEMCTL(1)",

    'php'       => "PHP(1)                    User Commands                   PHP(1)\n\nNAME\n       php - PHP Command Line Interface\n\nSYNOPSIS\n       php [options] [-r code] [--] [args...]\n       php [options] [-] [args...]\n       php [options] file [args...]\n\nDESCRIPTION\n       PHP is a widely-used general-purpose scripting language especially\n       suited for web development.\n\nOPTIONS\n       -v, --version\n              Print PHP version.\n\n       -i, --info\n              Print phpinfo() output.\n\n       -r code\n              Run PHP code without using script tags.\n\n       -m\n              List compiled-in modules.\n\n       -f file\n              Parse and execute file.\n\n       -c path\n              Look for php.ini file in this directory.\n\n       -d foo[=bar]\n              Define INI entry foo with value bar.\n\nEXAMPLES\n       php -v\n              Show PHP version.\n\n       php -r 'echo 1+1;'\n              Evaluate an expression.\n\n       php -i | grep memory\n              Show phpinfo and filter for memory settings.\n\n       php -m\n              List all loaded PHP modules.\n\nFILES\n       /etc/php.ini                   main configuration file\n       /etc/php.d/                    additional .ini files loaded automatically\n       /usr/lib64/php/modules/        compiled PHP extensions\n\nSEE ALSO\n       php-fpm(8)\n\nThe PHP Group                    March 2026                         PHP(1)",

    'zip'       => "ZIP(1)                    User Commands                   ZIP(1)\n\nNAME\n       zip - package and compress (archive) files\n\nSYNOPSIS\n       zip [OPTIONS] archive.zip file [file ...]\n\nDESCRIPTION\n       zip is a compression and file packaging utility.  The program places\n       one or more compressed files into a single ZIP archive, along with\n       information about the files (name, path, date, time of last\n       modification, protection, and check information to verify file\n       integrity).\n\nOPTIONS\n       -r, --recurse-paths\n              Travel the directory structure recursively.  For example:\n                zip -r foo.zip foo/\n\n       -v, --verbose\n              Verbose mode.\n\n       -u, --update\n              Replace (update) an existing entry in the zip archive only if\n              it has been modified more recently than the version already in\n              the zip archive.\n\n       -d, --delete\n              Remove (delete) entries from a zip archive.\n\nEXAMPLES\n       zip archive.zip file1.txt file2.txt\n              Create archive.zip from two files.\n\n       zip -r backup.zip /root/\n              Recursively archive the /root directory.\n\nSEE ALSO\n       unzip(1), tar(1)\n\nInfo-ZIP                         March 2026                         ZIP(1)",

    'unzip'     => "UNZIP(1)                  User Commands                 UNZIP(1)\n\nNAME\n       unzip - list, test and extract compressed files in a ZIP archive\n\nSYNOPSIS\n       unzip [OPTIONS] archive.zip [-d exdir]\n\nDESCRIPTION\n       unzip will list, test, or extract files from a ZIP archive, commonly\n       found on MS-DOS systems.\n\nOPTIONS\n       -l     List archive files (short format).\n\n       -v     List archive files verbosely.\n\n       -t     Test archive files.\n\n       -d exdir\n              An optional directory to which to extract files.\n              By default, all files and subdirectories are recreated in\n              the current directory.\n\nEXAMPLES\n       unzip archive.zip\n              Extract all files from archive.zip to the current directory.\n\n       unzip -l archive.zip\n              List the contents of archive.zip.\n\n       unzip archive.zip -d /tmp/\n              Extract archive.zip into /tmp/.\n\nSEE ALSO\n       zip(1), tar(1)\n\nInfo-ZIP                         March 2026                       UNZIP(1)",

    'rmdir'     => "RMDIR(1)                  User Commands                 RMDIR(1)\n\nNAME\n       rmdir - remove empty directories\n\nSYNOPSIS\n       rmdir [OPTION]... DIRECTORY...\n\nDESCRIPTION\n       Remove the DIRECTORY(ies), if they are empty.\n\n       -p, --parents\n              Remove DIRECTORY and its ancestors.  For example, 'rmdir -p\n              a/b/c' is similar to 'rmdir a/b/c a/b a'.\n\n       -v, --verbose\n              Output a diagnostic for every directory processed.\n\nEXIT STATUS\n       Returns 0 on success, non-zero if any error occurred.\n\nAUTHOR\n       Written by David MacKenzie.\n\nGNU coreutils                    March 2026                       RMDIR(1)",

    'du'        => "DU(1)                     User Commands                    DU(1)\n\nNAME\n       du - estimate file space usage\n\nSYNOPSIS\n       du [OPTION]... [FILE]...\n\nDESCRIPTION\n       Summarize device usage of the set of FILEs, recursively for\n       directories.\n\n       -s, --summarize\n              display only a total for each argument\n\n       -h, --human-readable\n              print sizes in human readable format (e.g., 1K 234M 2G)\n\n       -c, --total\n              produce a grand total\n\n       -d, --max-depth=N\n              print the total for a directory (or file, with --all) only\n              if it is N or fewer levels below the command line argument\n\nEXAMPLES\n       du -sh /var/log\n              Show total size of /var/log in human-readable form.\n\n       du -h /root\n              Show sizes of all files and dirs under /root.\n\nAUTHOR\n       Written by Torbjorn Granlund, David MacKenzie, and Paul Eggert.\n\nGNU coreutils                    March 2026                          DU(1)",

    'diff'      => "DIFF(1)                   User Commands                  DIFF(1)\n\nNAME\n       diff - compare files line by line\n\nSYNOPSIS\n       diff [OPTION]... FILES\n\nDESCRIPTION\n       Compare FILES line by line.\n\n       -u, -U NUM, --unified[=NUM]\n              Output NUM (default 3) lines of unified context.\n\n       -i, --ignore-case\n              Ignore case differences in file contents.\n\n       -r, --recursive\n              Recursively compare any subdirectories found.\n\n       -q, --brief\n              Report only when files differ.\n\n       -s, --report-identical-files\n              Report when two files are the same.\n\nOUTPUT FORMATS\n       Normal format\n              Each hunk is introduced by a line of the form:\n              r1 a r2     lines appended\n              r1 d r2     lines deleted\n              r1 c r2     lines changed\n\n       Unified format (-u)\n              Hunks introduced by @@ -l,s +l,s @@ lines; context\n              lines prefixed with space, deletions with -, additions with +.\n\nEXAMPLES\n       diff file1.txt file2.txt\n              Compare two files.\n\n       diff -u old.conf new.conf\n              Unified diff suitable for a patch file.\n\nAUTHOR\n       Written by Paul Eggert, Mike Haertel, David Hayes, Richard Stallman,\n       and Len Tower.\n\nGNU diffutils                    March 2026                        DIFF(1)",

    'passwd'    => "PASSWD(1)                 User Commands                 PASSWD(1)\n\nNAME\n       passwd - update user's authentication tokens\n\nSYNOPSIS\n       passwd [OPTION...] [LOGIN]\n\nDESCRIPTION\n       The passwd command changes passwords for user accounts.  A normal\n       user may only change the password for their own account, while the\n       superuser may change the password for any account.\n\n       -d, --delete\n              Delete a user's password (make it empty). Available to\n              root only.\n\n       -l, --lock\n              Lock the password of the named account. Available to\n              root only.\n\n       -u, --unlock\n              Unlock the password of the named account. Available to\n              root only.\n\n       -e, --expire\n              Immediately expire an account's password. Available to\n              root only.\n\n       -S, --status\n              Display account status information.\n\nFILES\n       /etc/passwd     user account information\n       /etc/shadow     secure user account information\n\nAUTHOR\n       Written by Marek Michalkiewicz.\n\nshadow-utils                     March 2026                      PASSWD(1)",

    'base64'    => "BASE64(1)                 User Commands                 BASE64(1)\n\nNAME\n       base64 - base64 encode/decode data and print to standard output\n\nSYNOPSIS\n       base64 [OPTION]... [FILE]\n       base64 [OPTION]... <<< STRING\n\nDESCRIPTION\n       Base64 encode or decode FILE, or standard input, to standard output.\n\n       With no FILE, or when FILE is -, read standard input.\n\n       -d, --decode\n              decode data\n\n       -i, --ignore-garbage\n              when decoding, ignore non-alphabet characters\n\n       -w, --wrap=COLS\n              wrap encoded lines after COLS character (default 76);\n              use 0 to disable line wrapping\n\nEXAMPLES\n       base64 <<< \"hello\"\n              Encode the string \"hello\" to base64.\n\n       base64 -d <<< \"aGVsbG8=\"\n              Decode a base64 string.\n\n       echo \"hello\" | base64\n              Pipe input to base64 for encoding.\n\nAUTHOR\n       Written by Simon Josefsson.\n\nGNU coreutils                    March 2026                      BASE64(1)",

    'bc'        => "BC(1)                     User Commands                    BC(1)\n\nNAME\n       bc - arbitrary precision calculator language\n\nSYNOPSIS\n       bc [OPTIONS] [FILE...]\n       bc <<< EXPRESSION\n\nDESCRIPTION\n       bc is a language that supports arbitrary precision numbers with\n       interactive execution of statements. There are some similarities\n       in the syntax to the C programming language.\n\n       -l, --mathlib\n              Define the standard math library.\n\n       -q, --quiet\n              Do not print the normal GNU bc welcome message.\n\n       -s, --standard\n              Process exactly the POSIX bc language.\n\nEXPRESSION SYNTAX\n       Arithmetic operators: + - * / ^ %\n       Grouping: ( )\n\nEXAMPLES\n       bc <<< \"2^10\"\n              Calculate 2 to the power of 10 (result: 1024).\n\n       bc <<< \"(3+4)*2\"\n              Calculate with parentheses (result: 14).\n\n       bc -l <<< \"scale=5; 1/3\"\n              Division with 5 decimal places.\n\nFILES\n       /usr/lib/bc/bc.l    math library (loaded with -l)\n\nAUTHOR\n       Philip A. Nelson. Current maintainer: GNU Project.\n\nGNU bc                           March 2026                          BC(1)",

    'tar'       => "TAR(1)                    User Commands                   TAR(1)\n\nNAME\n       tar - an archiving utility\n\nSYNOPSIS\n       tar [OPTION...] [FILE]...\n\nDESCRIPTION\n       GNU tar is an archiving program designed to store multiple files in a\n       single file (an archive), and to manipulate such archives.\n\nOPERATION MODES\n       -c, --create\n              Create a new archive.\n\n       -x, --extract, --get\n              Extract files from an archive.\n\n       -t, --list\n              List the contents of an archive.\n\nOPTIONS\n       -f, --file=ARCHIVE\n              Use archive file or device ARCHIVE.\n\n       -z, --gzip, --gunzip, --ungzip\n              Filter the archive through gzip.\n\n       -j, --bzip2\n              Filter the archive through bzip2.\n\n       -v, --verbose\n              Verbosely list files processed.\n\nEXAMPLES\n       tar -czf archive.tar.gz dir/\n              Create a gzip-compressed archive of dir/.\n\n       tar -xzf archive.tar.gz\n              Extract a gzip-compressed archive.\n\n       tar -tzf archive.tar.gz\n              List the contents of a gzip-compressed archive.\n\n       tar -cjf archive.tar.bz2 dir/\n              Create a bzip2-compressed archive of dir/.\n\nSEE ALSO\n       zip(1), unzip(1), gzip(1)\n\nGNU tar                          March 2026                         TAR(1)",

    'htop'      => "HTOP(1)                   User Commands                  HTOP(1)\n\nNAME\n       htop - interactive process viewer\n\nSYNOPSIS\n       htop [-d delay] [-u username] [-p pid[,pid...]]\n\nDESCRIPTION\n       htop is an interactive system-monitor process-viewer and\n       process-manager. It is designed as an alternative to the Unix\n       program top.\n\n       htop displays a frequently updated list of the processes running\n       on a computer, normally ordered by the amount of CPU usage.\n       Unlike top, htop provides a full list of processes running,\n       normally ordered by the amount of CPU usage. The display\n       includes per-CPU and memory/swap usage bars at the top.\n\nINTERACTIVE COMMANDS\n       q, F10   Quit\n       F6       Choose sort column\n       F9       Kill selected process\n       F5       Tree view\n       F3       Search processes\n       Up/Down  Move selection\n       Space    Tag/untag process\n\nOPTIONS\n       -d delay\n              Set the delay between updates, in tenths of a second.\n\n       -u username\n              Show only processes owned by username.\n\n       -p pid[,pid...]\n              Show only the given PIDs.\n\n       -s column\n              Sort by the specified column at startup.\n\nAUTHOR\n       Written by Hisham Muhammad.\n\nhtop                             March 2026                        HTOP(1)",

    'sort'      => "SORT(1)                   User Commands                  SORT(1)\n\nNAME\n       sort - sort lines of text files\n\nSYNOPSIS\n       sort [OPTION]... [FILE]...\n\nDESCRIPTION\n       Write sorted concatenation of all FILE(s) to standard output.\n\n       -r, --reverse\n              Reverse the result of comparisons.\n\n       -n, --numeric-sort\n              Compare according to string numerical value.\n\n       -u, --unique\n              With -c, check for strict ordering; without -c, output\n              only the first of an equal run.\n\n       -f, --ignore-case\n              Fold lower case to upper case characters.\n\n       -k, --key=KEYDEF\n              Sort via a key; KEYDEF gives location and type.\n              Example: -k2 sorts on the second whitespace-delimited field.\n\n       -t, --field-separator=SEP\n              Use SEP instead of non-blank to blank transition as the\n              field separator.\n\nEXAMPLES\n       sort file.txt\n              Sort file.txt alphabetically.\n\n       sort -r file.txt\n              Sort in reverse order.\n\n       sort -n numbers.txt\n              Sort numerically.\n\n       sort -u file.txt\n              Sort and remove duplicate lines.\n\n       sort -k2 file.txt\n              Sort by the second field.\n\n       sort -t: -k3 -n /etc/passwd\n              Sort /etc/passwd numerically by the third colon-delimited field.\n\nAUTHOR\n       Written by Mike Haertel and Paul Eggert.\n\nGNU coreutils                    March 2026                        SORT(1)",

    'uniq'      => "UNIQ(1)                   User Commands                  UNIQ(1)\n\nNAME\n       uniq - report or omit repeated lines\n\nSYNOPSIS\n       uniq [OPTION]... [INPUT]\n\nDESCRIPTION\n       Filter adjacent matching lines from INPUT, writing to standard\n       output.\n\n       Note: uniq only compares ADJACENT lines.  To collapse all\n       duplicates in a file, sort it first: sort file | uniq\n\n       -c, --count\n              prefix lines by the number of occurrences\n\n       -d, --repeated\n              only print duplicate lines, one for each group\n\n       -u, --unique\n              only print unique lines (appear exactly once)\n\n       -i, --ignore-case\n              ignore differences in case when comparing\n\nEXAMPLES\n       uniq file.txt\n              Remove adjacent duplicate lines.\n\n       sort file.txt | uniq\n              Remove ALL duplicate lines (sort first).\n\n       uniq -c file.txt\n              Count occurrences of each adjacent group.\n\n       uniq -d file.txt\n              Print only lines that are repeated.\n\n       uniq -u file.txt\n              Print only lines that appear exactly once.\n\nAUTHOR\n       Written by Richard M. Stallman and David MacKenzie.\n\nGNU coreutils                    March 2026                        UNIQ(1)",

    'joe'       => "JOE(1)                    User Commands                   JOE(1)\n\nNAME\n       joe - Joe's Own Editor\n\nSYNOPSIS\n       joe [OPTIONS] [file]\n\nDESCRIPTION\n       joe is a compact, easy-to-use text editor.  It uses ^K (Ctrl+K)\n       as a prefix for most multi-key commands, similar to WordStar and\n       Borland editors.\n\nKEY BINDINGS\n   FILE COMMANDS\n       ^KS        Save the current file (stay in editor)\n       ^KX        Save the current file and exit\n       ^KD        Save file with a new name (Save As)\n       ^KQ        Quit without saving\n       ^KR        Read (insert) another file at cursor\n\n   CURSOR MOVEMENT\n       ^F / ^B    Forward / Backward one character\n       ^N / ^P    Next line / Previous line\n       ^A         Go to beginning of line\n       ^E         Go to end of line\n       Alt+F      Move forward one word\n       Alt+B      Move backward one word\n       ^KU        Go to top of file\n       ^KV        Go to bottom of file\n       Arrow keys Move cursor\n       PageUp/Dn  Scroll by page\n\n   DELETION\n       ^D         Delete character under cursor\n       ^H / BS    Delete character to the left\n       ^Y         Delete (cut) entire line\n       ^W         Delete word to the right\n\n   BLOCK COMMANDS\n       ^KY        Delete marked block (or current line)\n       ^KC        Copy (paste cut buffer at cursor)\n       ^KM        Move (paste cut buffer at cursor)\n\n   SEARCH\n       ^KF        Find a string (enter search term, press Enter)\n       ^L         Repeat last search\n\n   HELP\n       ^KH        Toggle built-in help screen\n       F1         Toggle built-in help screen\n\nEXAMPLES\n       joe file.txt\n              Open file.txt for editing.\n\n       joe\n              Open joe with an empty buffer.\n\nAUTHOR\n       Written by Joseph H. Allen.\n\njoe                              March 2026                         JOE(1)",
];
